#!/bin/bash
############################
# Check autosign installation status.
output=$(sudo mokutil --import /etc/pki/akmods/certs/public_key.der)

# Check if the output contains the word "already enrolled"
if [[ $output == *"already enrolled"* ]]; then
    # If "already enrolled" is found, proceed with the first script
    echo "Secure boot key enrolled. Proceeding with fedora-postinstall.sh"
    # Add your code for Script 1 here
else
    # If "already enrolled" is not found, prompt the user to run a different script
    echo "Secure boot key not enrolled'."
    echo "Please run autosign"
    # Optionally, you can provide Script 2
#/mnt/Backup/Dropbox/Legion-linux/auto-sign.sh
#printf "Reboot now and enroll with the password!!"
fi
#
############################
## Grub
sudo dnf -y reinstall grub2-common
sudo grub2-editenv create
sudo grub2-mkconfig -o /boot/grub2/grub.cfg
sudo dracut -f --regenerate-all

############################
## Nvidia
sudo dnf update -y
sudo dnf install -y make gcc kernel-headers kernel-devel akmod-nvidia.x86_64 xorg-x11-drv-nvidia.x86_64 xorg-x11-drv-nvidia-cuda.x86_64 nvidia-settings.x86_64
sudo dracut -f --regenerate-all
sudo akmods --force
sudo dracut --force
############################
## Grub2 Theme
cd /tmp/
sudo dnf install git -y
git clone https://github.com/prasanthc41m/legion-grub.git
cd legion-grub
sudo bash install.sh
sudo grub2-mkconfig -o /boot/grub2/grub.cfg
#############################
## Folder Icon
sudo dnf install papirus-icon-theme -y
#############################
## Network Interface Old Names
cd /tmp/
touch 70-persistent-net.rules
cat > 70-persistent-net.rules <<EOL
# This file was automatically generated by the /lib/udev/write_net_rules
# program, run by the persistent-net-generator.rules rules file.
#
# You can modify it, as long as you keep each rule on a single
# line, and change only the value of the NAME= key.

# PCI device lan Device
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="88:a4:c2:b7:96:b9", ATTR{dev_id}=="0x0", ATTR{type}=="1", KERNEL=="eno*", NAME="eth0"

# PCI device Wlan Device
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="20:c1:9b:45:cc:8e", ATTR{dev_id}=="0x0", ATTR{type}=="1", KERNEL=="wl*", NAME="wlan0"

# USB device Wlan Device
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="00:c0:ca:75:e2:d5", ATTR{dev_id}=="0x0", ATTR{type}=="1", KERNEL=="wl*", NAME="wlan1"

# USB device lan Device
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="32:C5:F9:1E:55:2D", ATTR{dev_id}=="0x0", ATTR{type}=="1", KERNEL=="enp*", NAME="eth1"
'
EOL
sudo mv 70-persistent-net.rules /etc/udev/rules.d/70-persistent-net.rules	
sudo ln -s /dev/null /etc/udev/rules.d/80-net-setup-link.rules
###########################
## Conky
cd /tmp && sudo rm -rf auzia-conky* && git clone https://github.com/prasanthc41m/auzia-conky.git && cd auzia-conky && bash install.sh
###############################

## Repo amd gpu
sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
sudo dnf install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
#
### For switchable gpu
sudo dnf install -y xorg-x11-drv-amdgpu
### For switchable gpu
# Backup the original file
sudo cp /etc/default/grub /etc/default/grub.bak

# Find the GRUB_CMDLINE_LINUX line and extract the existing parameters
if grub_line=$(grep -e "^GRUB_CMDLINE_LINUX=" /etc/default/grub); then
  # Extract the content within the quotes
  current_params=$(echo "$grub_line" | sed -n 's/^GRUB_CMDLINE_LINUX="\([^"]*\)"/\1/p')

  # Add the new parameter
  new_params="$current_params rd.driver.pre=amdgpu"

  # Construct the new GRUB_CMDLINE_LINUX line
  new_grub_line="GRUB_CMDLINE_LINUX=\"$new_params\""

  # Replace the old line with the new line
  sudo sed -i "s/^GRUB_CMDLINE_LINUX=\"[^\"]*\"/$new_grub_line/" /etc/default/grub

  # Update GRUB
  sudo grub2-mkconfig -o /boot/grub2/grub.cfg

  # Verify the changes
  grep -e "^GRUB_CMDLINE_LINUX=" /etc/default/grub

  echo "GRUB configuration updated successfully."
else
  echo "Error: GRUB_CMDLINE_LINUX not found. Check your /etc/default/grub file."
  exit 1
fi
#
###############################

## Applications
sudo dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm 
curl -fsSl https://pkg.cloudflareclient.com/cloudflare-warp-ascii.repo | sudo tee /etc/yum.repos.d/cloudflare-warp.repo
sudo wget -O /etc/yum.repos.d/microsoft-prod.repo https://packages.microsoft.com/yumrepos/edge/config.repo
sudo dnf copr enable aleasto/waydroid
sudo dnf update -y
#
sudo dnf install -y htop nload speedtest-cli hwinfo.x86_64 hicolor-icon-theme.noarch lm_sensors.x86_64 bluez google-chrome-stable nmap photorec solaar easyeffects.x86_64 qpwgraph.x86_64 radeontop lutris.x86_64   pavucontrol.x86_64 microsoft-edge-stable.x86_64 waydroid perl-Image-ExifTool vlc vlc-extras helvum.x86_64 @development-tools dkms VirtualBox.x86_64 virtualbox-guest-additions.x86_64 onedrive.x86_64 wireshark.x86_64 filezilla.x86_64 snapd luckybackup.x86_64 piper  cloudflare-warp.x86_64
## Youtube issue fix
sudo dnf swap ffmpeg-free ffmpeg --allowerasing -y
sudo dnf4 groupupdate multimedia --setop="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin  -y
sudo dnf4 groupupdate sound-and-video -y
# You may also need to manually start the service
#
sudo systemctl --user enable onedrive
sudo systemctl --user start onedrive
#
## add user to group
sudo usermod -a -G wireshark $USER
sudo usermod -a -G vboxusers $USER
#
ln -s /mnt/Data/OS/VBoxGuestAdditions_7.0.8.iso ~/.config/VirtualBox/
sudo akmods; systemctl restart vboxdrv.service

#
warp-cli registeration
#
sudo snap install bitwarden 
#
flatpak install -y  fr.romainvigier.MetadataCleaner com.belmoussaoui.Obfuscate cc.arduino.IDE2 us.zoom.Zoom io.freetubeapp.FreeTube nz.mega.MEGAsync org.tigervnc.vncviewer com.spotify.Client org.raspberrypi.rpi-imager  com.github.ADBeveridge.Raider
#
#############################
## Pipewire
easyeffects -q
cd /tmp
git clone https://github.com/prasanthc41m/EasyEffects-Presets.git
cd EasyEffects-Presets
cp *.json ~/.config/easyeffects/output/
#
cd /tmp
git clone https://github.com/prasanthc41m/EasyEffects-Presets-2.git
cd EasyEffects-Presets-2
cp LoudnessEqualizer.json ~/.config/easyeffects/output/
#
cd /tmp
git clone https://github.com/prasanthc41m/pipewire.git
sudo cp pipewire/bt-audio.desktop /usr/share/applications/
sudo cp -r pipewire /opt/
#############################
## DEB Applications
cd /tmp
sudo dnf update -y
sudo dnf install openssl xdg-utils ffmpeg -y
#curl https://dn3.freedownloadmanager.org/6/latest/freedownloadmanager.deb -o freedownloadmanager.deb
#mkdir -p freedownloadmanager
#cd freedownloadmanager
#ar x ../freedownloadmanager.deb
#sudo tar -xvJf data.tar.xz -C /
#sudo tar -xvzf data.tar.gz -C /
#
#############################
## Web WhatsApp Linux Application
cd /tmp/
rm -rf /tmp/whatsapp-linux-build-dir
mkdir -p whatsapp-linux-build-dir
cd whatsapp-linux-build-dir

curl -o icon.png https://static.whatsapp.net/rsrc.php/v4/yP/r/rYZqPCBaG70.png
#wget https://static.whatsapp.net/rsrc.php/v4/yP/r/rYZqPCBaG70.png -O icon.png
#convert -resize 256x256^ icon.png icon.png

sudo dnf install npm -y
sudo npm install -g nativefier
nativefier -p linux -a x64 -i icon.png --disable-context-menu --disable-dev-tools --single-instance https://web.whatsapp.com/
sudo mv WhatsAppWeb-linux-x64 whatsapp
sudo rm -rf /opt/whatsapp
sudo mv /tmp/whatsapp-linux-build-dir/whatsapp /opt
sudo mv /opt/whatsapp/WhatsAppWeb  /opt/whatsapp/whatsapp
sudo chmod 755 -R /opt/whatsapp/

echo -e "[Desktop Entry]\n Type=Application\n Exec=/opt/whatsapp/whatsapp %F\n Name=WhatsApp\n Icon=/opt/whatsapp/resources/app/icon.png\n Categories=Network;InstantMessaging;\n X-WebApp-URL=https://web.whatsapp.com\n MimeType=text/html;text/xml;application/xhtml_xml;\n Terminal=false\n StartupNotify=true" > /tmp/whatsapp.desktop

sudo mv /tmp/whatsapp.desktop /usr/share/applications/
nohup /opt/whatsapp/whatsapp %F &
#sudo nano /usr/share/applications/whatsapp.desktop
#
# Get the first part of WM_CLASS
wm_class=$(xprop | grep WM_CLASS | awk -F'"' '{print $2}')

# Check if WM_CLASS was found
if [ -n "$wm_class" ]; then
  # Check if the file exists, if not create it.
  if [[ ! -f /usr/share/applications/whatsapp.desktop ]]; then
        touch /usr/share/applications/whatsapp.desktop
  fi

  # Add or replace the StartupWMClass line in the file
  sudo sed -i "/^StartupWMClass=/d" /usr/share/applications/whatsapp.desktop
  sudo echo "StartupWMClass=$wm_class" | sudo tee -a /usr/share/applications/whatsapp.desktop

  echo "StartupWMClass added to whatsapp.desktop: $wm_class"
else
  echo "Error: Could not determine WM_CLASS."
fi
#
## Lenovo Legion Linux Support
cd /tmp/
wget https://copr.fedorainfracloud.org/coprs/mrduarte/LenovoLegionLinux/repo/fedora-41/mrduarte-LenovoLegionLinux-fedora-41.repo
sudo dnf config-manager addrepo --from-repofile=mrduarte-LenovoLegionLinux-fedora-41.repo
sudo dnf upgrade -y
sudo dnf install -y dkms-LenovoLegionLinux python-darkdetect python-LenovoLegionLinux
#
###
 sudo akmods --force --rebuild
#############################
echo "Installation success, reboot.."
#############################
